### Problem 2

First of all, we need to define the first equipartition projection. This is done below, and tested on a simple array.

In [24]:
import numpy as np
import matplotlib.pyplot as plt
from RRR import *

t = 3*4*5
sparse = 11

a = np.random.rand(3, 4, 5)


def sumProj(tensor, target):
    s = np.sum(tensor)
    h = np.shape(tensor)
    l = np.prod(h) #total # of elements in tensor
    a = (target - s)/l
    return tensor + (a*np.ones(h))

def transposeAxes(target, length):
    l = range(length)
    l[target] = 0
    l[0] = target
    return tuple(l)

def equiPartProj(tensor, target=1.0):
    h = np.shape(tensor)
    for i in range(len(h)):                                 #Iterate the axes
        ax = transposeAxes(i, len(h))
        tensor = np.transpose(tensor, ax)                   #Rotate
        for j in range(h[i]):                               #Iterate the slices
            tensor[j] = sumProj(tensor[j], target/h[i])     #Project
        tensor = np.transpose(tensor, ax)                   #Rotate back
    return tensor

a = equiPartProj(a)

print a



[[[ 0.00342669 -0.23124228 -0.22957285  0.46398499  0.24348072]
  [-0.20655329  0.40445812 -0.26976341  0.03983618 -0.0551872 ]
  [-0.06961032  0.20964774 -0.05209812  0.19625786  0.3922882 ]
  [ 0.21885806 -0.18325183 -0.09350448 -0.24129899 -0.20682244]]

 [[ 0.462947   -0.35514694  0.42041176 -0.21998205 -0.46757468]
  [-0.37244154  0.24850722  0.0621213   0.31493265  0.28670965]
  [-0.31123156  0.4502531   0.19545004 -0.22305835 -0.25062949]
  [ 0.4783962  -0.35180187 -0.01635168  0.11928833 -0.13746576]]

 [[ 0.04749831  0.32311473 -0.04149538 -0.32980667  0.15995665]
  [-0.33771191 -0.3508337   0.08758526  0.2172082   0.18113247]
  [ 0.3139203  -0.10523059 -0.25146978 -0.20798938 -0.03649965]
  [-0.02749794  0.1415263   0.38868735  0.07062723  0.09061152]]]


Next, we need to write a sparsity projection routine.

We will test it on the same array.

In [25]:
def sparseProj(tensor, sparsity=sparse):
    h = np.shape(tensor)
    t2 = tensor.reshape(np.prod(h))  #Go to one dimension
    indeces = np.argsort(t2)
    revIndeces = np.argsort(indeces)
    t3 = t2[indeces]
    t3[:-sparsity] = 0.
    for i in range(-sparsity, 0):
        if t3[i] < 0:
            t3[i] = 0.
    t2 = t3[revIndeces]
    return np.reshape(t2, h)

a = sparseProj(a)

print a

[[[ 0.          0.          0.          0.46398499  0.        ]
  [ 0.          0.40445812  0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.3922882 ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.462947    0.          0.42041176  0.          0.        ]
  [ 0.          0.          0.          0.31493265  0.        ]
  [ 0.          0.4502531   0.          0.          0.        ]
  [ 0.4783962   0.          0.          0.          0.        ]]

 [[ 0.          0.32311473  0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.        ]
  [ 0.3139203   0.          0.          0.          0.        ]
  [ 0.          0.          0.38868735  0.          0.        ]]]


Finally, we will need to create random arrays somehow, and test the projections on them.

After that, we can simply use the RRR routine and run the code.

In [38]:
a = np.random.rand(3, 4, 5)

b, errors = RRR(a, equiPartProj, sparseProj, 0.5, 1e-4, 10000, True)

print t*sparseProj(b)
#print errors[0]
#plt.plot(range(len(errors)), errors)
#plt.show()

[[[  0.          19.53617158   0.           0.           0.        ]
  [  0.           0.           0.           0.          23.84064613]
  [  0.          19.46446777   0.           0.           0.        ]
  [ 19.55179681   0.           0.           0.           0.        ]]

 [[ 19.83961433   0.           0.           0.           0.        ]
  [  0.          23.09373511   0.           0.           0.        ]
  [  0.           0.          17.78362315  21.72211082   0.        ]
  [  0.           0.          36.89800957   0.           0.        ]]

 [[ 19.85756608   0.           0.           0.           0.        ]
  [  0.           0.          22.10287702   0.           0.        ]
  [  0.           0.           0.           0.           0.        ]
  [  0.           0.           0.           0.           0.        ]]]
